syntax = "proto3";

package indicator;


service IndicatorService {
  rpc ComputeSma(SmaRequest) returns (SmaResponse);
  rpc ComputeEma(EmaRequest) returns (EmaResponse);
  rpc ComputeRsi(RsiRequest) returns (RsiResponse);
}

message SmaRequest {
  repeated double values = 1;
  int32 period = 2;
}

message SmaResponse {
  repeated double result = 1;
}

message EmaRequest {
  repeated double values = 1;
  int32 period = 2;
}

message EmaResponse {
  repeated double result = 1;
}

message RsiRequest {
  repeated double values = 1;
  int32 period = 2;
}

message RsiResponse {
  repeated double result = 1;
}
